### ISSUE TITLE
Unable to monitor sidekiq

### ISSUE THREAD

**Issue by jfabre** [mperham/inspeqtor#100]
Hello, 

Inspeqtor 0.8.1, ubuntu 12.04, Sidekiq 3.3.4
I'm using upstart.

I'm trying to monitor memory usage on sidekiq using Inspeqtor.
Somehow, it seems like inspeqtor is not tracking sidekiq properly.

Here's what I get when I run the status command: 
```
inspeqtorctl status
Inspeqtor 0.8.1, uptime: 22m6.373311955s, pid: 19962

Host: ip-172-31-42-196
  cpu                                 0.3%
  cpu:iowait                          0.0%
  cpu:steal                           0.1%
  cpu:system                          0.1%
  cpu:user                            0.1%
  disk:/                              46.0%           90%
  load:1                              0.00
  load:15                             0.05
  load:5                              0.01            10
  swap                                0.0%            20%

Service: sidekiq [Unknown/0]
  cpu:system                          0.0%
  cpu:total_system                    0.0%
  cpu:total_user                      0.0%
  cpu:user                            0.0%            90%
  memory:rss                          -0.00m          2g
```
I used the upstart scripts given in sidekiq, but did change them a little to accomodate my needs.
Any idea on why it would do this?

Thanks.

**Comment by mperham** [comment]
Your upstart script isn't starting sidekiq properly so it's tracking the wrong PID.

**Comment by jfabre** [comment]
Thanks for the quick reply, I'll have a look!

**Comment by jfabre** [comment]
When I do:
```
initctl list | grep sidekiq
sidekiq-manager start/running
sidekiq (/path/to/app-0) start/running, process 21650
```
does that mean I have to track "sidekiq (/path/to/app-0)" in inspeqtor, or still just sidekiq?

**Comment by mperham** [comment]
Show your upstart .conf for Sidekiq.

**Comment by jfabre** [comment]
```upstart
description "Sidekiq Background Worker"

# This starts upon bootup and stops on shutdown
start on runlevel [2345]
stop on (stopping sidekiq-manager or runlevel [06])


env HOME=/home/ubuntu

respawn
respawn limit 3 30

# TERM is sent by sidekiqctl when stopping sidekiq.  Without declaring these as normal exit codes, it just respawns.
normal exit 0 TERM

instance ${app}-${index}

script
# this script runs in /bin/sh by default
# respawn as bash so we can source in rbenv
exec /bin/bash <<'EOT'
 
  source /home/ubuntu/envs/${env}

  logger -t sidekiq "Starting process: $app-$index"

  # Logs out to /var/log/upstart/sidekiq.log by default

  cd $app
  exec bin/sidekiq -i ${index} -e production -P ${app}/tmp/pids/sidekiq-${index}.pid
EOT
end script

pre-stop script
# this script runs in /bin/sh by default
# respawn as bash so we can source in rbenv
exec /bin/bash <<'EOT'
  source /home/ubuntu/envs/${env}

  logger -t sidekiq "Stopping process: $app-$index"

  # Logs out to /var/log/upstart/sidekiq.log by default

  cd $app
  exec bundle exec sidekiqctl stop ${app}/tmp/pids/sidekiq-${index}.pid 2> /dev/null
EOT
end script
```

**Comment by mperham** [comment]
The pre-stop section is unnecessary. Upstart sends TERM by default. 

I suspect the issue is that Inspeqtor does not support instance tasks. If you want N different processes, you need to create N confs.

**Comment by jfabre** [comment]
That was the issue. 
Everything seems to work now.
Thank you so much for taking the time to help me.

**Comment by sorentwo** [comment]
@mperham: I don't see a straightforward way to handle upstart instance tasks. It's effectively the same as a parent process that spawns workers (Unicorn/Puma). The approach that was taken with `total_rss` could work, but you'd probably want something in the Inspeqtor service config to indicate that the upstart job is spawning instances.

Or, alternatively we can just deter people from using instance jobs altogether and document it as a caveat.

**Comment by mperham** [comment]
I don't see any good solution. I'd like for an easier way for people to start up a cluster of Sidekiqs. Is there a generic project which can fork off N instances of a command and allows managing them?  Sort of a generic clustering manager?

**Comment by tildeslash** [comment]
>  Is there a generic project which can fork off N instances of a command and allows managing them?  Sort of a generic clustering manager?

Yes, Monit  :-)
