### ISSUE TITLE
inspeqtorctl start deploy is on, still get alerts

### ISSUE THREAD

**Issue by allaire** [mperham/inspeqtor#103]
`start deploy` is not working in both Capistrano and via ssh in cmd (`sudo inspeqtorctl start deploy`).

Getting a swap host email alert:
`swap is greater than than 20% for stg`

the doc says it should not trigger any actions during deploy: https://github.com/mperham/inspeqtor/wiki/Commands#supported-commands

```
app@stg:~$ sudo inspeqtor -v
Inspeqtor 0.8.1
Copyright © 2015 Contributed Systems LLC
Licensed under the GNU Public License 3.0
```

**Comment by allaire** [comment]
I think this might be related: https://github.com/mperham/inspeqtor/pull/76

**Comment by sorentwo** [comment]
@allaire: There shouldn't be any difference between host and service rules, they are wrapped in the same `silenced` check here: https://github.com/mperham/inspeqtor/blob/master/inspeqtor.go#L307

**Comment by allaire** [comment]
@sorentwo Ah, well no dice, it's not working on my side, even when I do `start deploy` in ssh 1 min. before deploying...

**Comment by sorentwo** [comment]
@allaire: I think we'll need more context to diagnose the issue. Is it easily reproducible, can you do it in a staging environment? Can you share the host config and typical output of `inspeqtorctl status` before deployment?

**Comment by allaire** [comment]
@sorentwo Will report back soon, thanks!

**Comment by allaire** [comment]
@sorentwo 

Here's the status:

```
Inspeqtor 0.8.1, uptime: 5h10m55.765117427s, pid: 26255

Host: stg
  cpu                                 2.6%
  cpu:iowait                          0.2%
  cpu:steal                           0.2%
  cpu:system                          1.1%
  cpu:user                            1.1%
  disk:/                              41.0%           90%
  load:1                              0.08
  load:15                             0.05
  load:5                              0.03            10
  swap                                20.0%           20%

Service: app-web-1 [Up/6381]
  cpu:system                          0.0%
  cpu:total_system                    0.0%
  cpu:total_user                      0.0%
  cpu:user                            0.0%
  memory:rss                          9.00m
  memory:total_rss                    1010.38m        1g

Service: app-worker-1 [Up/27186]
  cpu:system                          0.1%
  cpu:total_system                    0.0%
  cpu:total_user                      0.0%
  cpu:user                            0.1%
  memory:rss                          266.44m
  memory:total_rss                    266.44m         600m
```

Here's my host config:

```
#
# Inspeqtor's default host check.
#
# .inq files represent a thing to monitor and verify.
# Inspeqtor MUST, at minimum, have a "check host" recipe
# in /etc/inspeqtor/host.inq
#
check host

  #
  # Typically you want to use all your RAM but not go into swap.
  # We'll trigger an alert if the system uses more than 20% swap.
  #
  if swap > 20% then alert

  #
  # Verify the machine isn't overloaded.  This is a rough rule,
  # edit as necessary for your machine.
  #
  if load:5 > 10 then alert

  #
  # Running out of disk space will not make you look good to the boss.
  # Alert if the root partition is running out of space.
  #
  # You can add any mount point, e.g.
  #    if disk:/backups > 90% then alert
  #
  if disk:/ > 90% then alert
```

This problem occurs on my staging environment.

**Comment by allaire** [comment]
@sorentwo @mperham Is it because the hooks in the `capistrano-inspeqtor` not correctly hooked in the deploy flow? https://github.com/seuros/capistrano-inspeqtor/blob/master/lib/capistrano/tasks/inspeqtor.rake#L27-L30 (http://capistranorb.com/documentation/getting-started/flow/) ? Maybe the `start deploy` is triggered too late?

**Comment by sorentwo** [comment]
@allaire: the deploy start should be triggered right away or it could interfere. The simplest way to diagnose whether this is happening during a deploy is with a custom build that logs the `silence` value when metrics are gathered and logs transitions in or out of silence mode.

**Comment by allaire** [comment]
Having 0 experience with Go, this is going to be hard for me with the work I have in the upcoming weeks, might just enjoy these notifications when I deploy :)

**Comment by sorentwo** [comment]
No worries! If you like I can provide you with a build to try out. I understand that getting the project set up can be daunting.

**Comment by allaire** [comment]
@sorentwo Sorry for the delay, you can go ahead, we're getting pretty tired of all these emails now :P

**Comment by mperham** [comment]
Can you turn on verbose logging and gist the output before/during/after a deploy?

**Comment by allaire** [comment]
@mperham Will do this week. What's the easiest way to do this if I run Inspeqtor in Ubuntu via apt package (I'm using https://github.com/mlafeldt/inspeqtor-cookbook/)

**Comment by mperham** [comment]
Iirc you can edit /etc/inspeqtor/inspector.conf to adjust the log level.

**Comment by allaire** [comment]
@mperham Thanks for the logging trick, I found the issue, it was related to the capistrano task not using `inspeqtorctl`.

https://github.com/seuros/capistrano-inspeqtor/pull/4/files
