### ISSUE TITLE
First email alert via gmail triggers "sign-in attempt prevented"

### ISSUE THREAD

**Issue by sorentwo** [mperham/inspeqtor#107]
The result of the first time I triggered an email alert for a new Inspeqtor install:

<img width="610" alt="screen shot 2015-08-21 at 11 42 25 am" src="https://cloud.githubusercontent.com/assets/270831/9413780/c0bfa2f0-47f9-11e5-9256-0e80a99d8c50.png">

As you can see, the exact cause for why it was "insecure" isn't stated. This certainly isn't the experience we want.

**Comment by mperham** [comment]
Ugh, no idea why it's considered insecure.  It should be using SMTP/tls.

**Comment by Paxa** [comment]
I had same problem before, I solved my making ssh tonel to server and open gmail with browser, but that was long time ago.

It's more easy to set up with mail services, such as mailgun, amazon ses, sendgrid, etc.. Free quota should be enough, gmail also has limitations in mails per day that you can send

**Comment by sorentwo** [comment]
I'm unable to recreate this. It has worked since I opened the issue, so I'll write it off as a fluke.
