### ISSUE TITLE
Logger for centos 6

### ISSUE THREAD

**Issue by Paxa** [mperham/inspeqtor#109]
On CentOs 6 logging doesn't work.

To fix it open file `/etc/init/inspeqtor.conf`
Find line `exec /usr/bin/inspeqtor -c /etc/inspeqtor -s /var/run/inspeqtor.sock`

To log in `/var/log/messages`:
```
exec /usr/bin/inspeqtor -c /etc/inspeqtor -s /var/run/inspeqtor.sock | logger -t inspeqtor
```
To log in `/var/log/inspeqtor.log`:
```
exec /usr/bin/inspeqtor -c /etc/inspeqtor -s /var/run/inspeqtor.sock >> /var/log/inspeqtor.log 2>&1
```

**Comment by mperham** [comment]
"Logging doesn't work" what does that mean?  Please be more specific.

**Comment by mperham** [comment]
Inspeqtor assumes an Upstart version that is sane: it should redirect any standard output to some file in `/var/log/upstart`.  Looks like this was added in Upstart 1.4 and I assume CentOS 6 is using some ancient Upstart version.

http://upstart.ubuntu.com/cookbook/#obtaining-a-log-of-a-script-section

**Comment by sorentwo** [comment]
As a separate note, piping into a logger process within the exec block will make upstart track the pid of the logger process, not the Inspeqtor process. That will cause trouble when you go to start, stop, or restart.

**Comment by mperham** [comment]
Yep, you should re-exec to redirect stdout before exec'ing inspeqtor:

```
exec >> /var/log/inspeqtor.log 2>&1
exec /usr/bin/inspeqtor ...
```

**Comment by mperham** [comment]
I should note that I don't know of a "clean" way to fix this so I don't plan to fix it.  CentOS 6 is a small enough demographic that I can't justify it.  If you know of a clean way to fix it, I'll consider it.

**Comment by Paxa** [comment]
Thanks for explanation
