### ISSUE TITLE
Go get fails

### ISSUE THREAD

**Issue by moomerman** [mperham/inspeqtor#111]
```
[mba ~]$ go version
go version go1.5.1 darwin/amd64
[mba ~]$ go get github.com/mperham/inspeqtor
# github.com/mperham/inspeqtor
go/src/github.com/mperham/inspeqtor/actions.go:27: undefined: Asset
[mba ~]$ 
```

**Comment by mperham** [comment]
Inspeqtor is an application, not a library.  You can't `go get` it.  You need to git clone it and then run `make prepare`.

**Comment by moomerman** [comment]
Thanks for the response! I'm relatively new to go and assumed you could go get any repo.
