### ISSUE TITLE
Where to find make.bash?

### ISSUE THREAD

**Issue by Paxa** [mperham/inspeqtor#114]
Wiki says:
```
cd /usr/local/opt/go/libexec/src
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 ./make.bash --no-clean
```

I can't find make.bash, is it part of inspeqtor source?

**Comment by sorentwo** [comment]
This is part of how Go cross compiles, not anything that Inspeqtor is doing. If you list the contents of `/usr/local/opt/go/libexec/src` you'll see that `make.bash` is in the directory, so it should work.

As it looks like you used Homebrew for the install, you may reinstall with `--cross-compile-all`, which will automatically set you up for all cross compilation.

```bash
brew reinstall go --cross-compile-all
```

Either way, this is something that comes from Go. There is a *lot* of information about fixing it online.
