### ISSUE TITLE
Docker + supervisord

### ISSUE THREAD

**Issue by rmetzler** [mperham/inspeqtor#115]
A lot of people use an init process in their Docker containers. Often they use supervisord.

There is a restart flag in Containers, but I guess an alerting tool like inspeqtor would be useful.

**Comment by sorentwo** [comment]
The inspeqtor policy has been no feature requests, only pull requests. Any additions need to be championed / developed by somebody who actually uses the requested technology.

Supervisord certainly would be useful, and getting in on the docker scene would be great, so please do consider working on a PR.
