### ISSUE TITLE
No way (at least isn't documented) to monitor overall host's memory

### ISSUE THREAD

**Issue by netkgk** [mperham/inspeqtor#116]
I was unpleasantly surprised when couldn't find this _very basic_ feature. This is kind of _must have_ for monitoring solution. Per-process memory metrics won't help.

**Comment by sorentwo** [comment]
You can definitely track the memory usage for an entire host. Those settings are configured per host, not per process, so they go in `host.inq`. There are details about which values can be tracked in the wiki.

**Comment by netkgk** [comment]
https://github.com/mperham/inspeqtor/wiki/Metrics
Which one metric from the _Host-wide_ section collects the memory?

**Comment by mperham** [comment]
@netkgk You cannot get total host memory in use, only swap.

**Comment by netkgk** [comment]
Please reopen the issue, then. This is definitely a bug.

**Comment by mperham** [comment]
It's not a bug it's a feature request. Would you tell me exactly where to get the value you want to monitor?

**Comment by tioteath** [comment]
Is that feature already implemented? It's not clear if it is and issue is closed.

**Comment by vifreefly** [comment]
> It's not a bug it's a feature request. Would you tell me exactly where to get the value you want to monitor?

Digital Ocean Monitoring https://www.digitalocean.com/products/monitoring/ has this host specific metric called **Memory Utilization**:
![](https://i.imgur.com/9C1rB9m.png)

To collect the stats there should be installed do-agent on the remote server. They are open sourced the agent, which is btw **written in Go** https://github.com/digitalocean/do-agent 

@mperham
