### ISSUE TITLE
PID detection is broken for sysvinit

### ISSUE THREAD

**Issue by tioteath** [mperham/inspeqtor#117]
subj. due to this code:
```
	paths := []string{
		i.varrunPath + serviceName + ".pid",
		i.varrunPath + serviceName + "/" + serviceName + ".pid",
	}
```

So PID file names are hardcoded and it seems there's no way to set that path manually. Like half of sysvinit's services set its own PID's name in `/run`, mine is `/run/postgresql/9.3-main.pid`,  so it must be possible to point inspeqtor to proper one, as those locations are in correspondence with the standard (it doesn't enforces PID names, only paths, as far as I know .

 Settings symlinks is not an option, as it must be performed each reboot and there's no good place to put this symlink creation code to. Changing init script, provided by the package is _allways_ the worst option.

**Comment by jwmarshall** [comment]
I have the same issue with postgresql though my pidfile is in a different location. Could we allow and override in the configuration perhaps?

In the case above something like:
```
check service postgresql
    with pidfile "/run/postgreql/9.3-main.pid"
```

**Comment by mperham** [comment]
Put in a soft link?

**Comment by jwmarshall** [comment]
Soft link works for me. But may not be ideal in all cases.
