### ISSUE TITLE
`swap` metric question 

### ISSUE THREAD

**Issue by duhast** [mperham/inspeqtor#119]
Hello!

A have a question about `swap` host-wide metric.
I've notes several emails from Inspeqtor about swap is greater than treshold:

```
swap is greater than than 20% for test-thin

Current:   100.0%
Threshold: 20%
```

`stats` gives the following:
```
Inspeqtor 1.0.0, uptime: 24m2.996706422s, pid: 12638

Host: test-thin
  cpu                                 0.6%           
  cpu:iowait                          0.0%           
  cpu:steal                           0.1%           
  cpu:system                          0.2%           
  cpu:user                            0.3%           
  disk:/                              10.0%           90%
  load:1                              0.00           
  load:15                             0.05           
  load:5                              0.01            10
! swap                                100.0%          20%

Service: thin [Up/10920]
  cpu:system                          0.0%           
  cpu:total_system                    0.0%           
  cpu:total_user                      0.0%            90%
  cpu:user                            0.1%           
  memory:rss                          90.80m         
  memory:total_rss                    90.80m          768m
```

OS is Ubuntu:
`Linux version 3.13.0-58-generic (buildd@allspice) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #97-Ubuntu SMP Wed Jul 8 02:56:15 UTC 2015`

`free -m` and `top` show that no swap is used:
```
             total       used       free     shared    buffers     cached
Mem:           988        737        251          0         17        519
-/+ buffers/cache:        200        788
Swap:            0          0          0

```

The question is why Inspeqtor may report `swap` metric incorrectly?

**Comment by sorentwo** [comment]
The swap issue is common for Ubuntu and virtual machines. There is an article from Digital Ocean that outlines how to enable swap, which will get actual swap working and allow inspeqtor to report it correctly.

https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04

**Comment by mperham** [comment]
You don't have swap enabled, therefore Inspeqtor thinks you are using 100% of 0 swap.  If you want to monitor swap, by definition you should turn it on.

**Comment by duhast** [comment]
Ok, and since i don't want to add a swap partition it seems I should just ignore this metric, correct? 
Is there any way to disable reports on `swap` in Inspeqtor?

**Comment by sorentwo** [comment]
@duhast Your host wide metrics are set to monitor swap, you can remove the check there to disable it. I forgot that it is there by default and assumed you were intentionally monitoring swap.

**Comment by duhast** [comment]
Got it, thanks for your quick replies guys!
