### ISSUE TITLE
bizarre test failures on linux-amd64 when using go 1.5.3

### ISSUE THREAD

**Issue by bneumeier** [mperham/inspeqtor#120]
I am trying to build inspeqtor master (ea2f3fa26f4e0e136ab26cb3bba2ba8421fdd3fb), using a freshly-built go 1.5.3 that passed all its self-tests.

"make prepare" completes without incident. "make" reports a bunch of test failures, which all have the same basic format, e.g.:

```
--- FAIL: TestRestart (0.00s)
        Error Trace:    actions_test.go:37
	Error:		Not equal: "Up" (expected)
			        != "Up" (actual)
```

As far as I can tell, the expected value matches the actual value for all of the test failures, but is regarded as not being equal. Any idea why that would be happening?

**Comment by sorentwo** [comment]
Sorry to say that I have no idea. I've always had rotten luck getting go tests to play nicely. I don't think this is really an inspeqtor issue though, so I'm going to close this for the time being.
