### ISSUE TITLE
Alternative to packagecloud.io

### ISSUE THREAD

**Issue by hendricius** [mperham/inspeqtor#121]
We just had a funny problem with packagecloud.io. Their repo was offline, but our deployment scripts required inspeqtor to be installed via their service. Yum then failed to set up the server and thus all our new automatically instances failed to launch.

Is there an alternative to packagecloud.io for setting up the servers using the provided binaries?

**Comment by mperham** [comment]
No alternative source for packages.  You can build from source or self-host the packages.

**Comment by hendricius** [comment]
Thanks. I am hosting the binary myself now on S3. That way things like that can no longer happen :)
