### ISSUE TITLE
Monitor a services without memory/cpu metrics

### ISSUE THREAD

**Issue by jwmarshall** [mperham/inspeqtor#123]
Is it possible to monitor services without metrics? From what I've experienced an INQ without rules is skipped by inspeqtor. 

Some of processes I want to monitor will at some point in their life (likely several times a day) use large amounts of memory and/or cpu, but I want to ensure that they don't crash or stop working, and if so alert and restart them. For now I can probably get around this by increasing the COUNT for these rules, but that feels like a bit of a hack.

Examples of this with monit would be:

Simply checks the process is running and matches the pid
```
check process nginx with pidfile /var/run/nginx.pid
```

Even a simple port check would work for some cases I have, but not all.
```
check process nginx with pidfile /var/run/nginx.pid
    if failed port 80 for 2 cycles then restart
```

Thanks!

**Comment by mperham** [comment]
Afaik not today. Add a check for a limit which will never be met.
