### ISSUE TITLE
postgresql service ignoring .pgpass

### ISSUE THREAD

**Issue by jmliu** [mperham/inspeqtor#125]
When I try to start inspector, it fails to start since the postgresql service errors and this appears in the log:

```
Password for user <db_username>:
psql: fe_sendauth: no password supplied
```

I'm able to login to `psql` from the command line without providing the password otherwise, so I'm stuck as to why the `.pgpass` file is being ignored through inspeqtor.

**Comment by sorentwo** [comment]
The pgpass file has very specific permission requirements. That has been the reason it fails in all of my experience.

This isn't Inspeqtor specific, you can recreate it by attempting to connect with an unprivileged user.

**Comment by jmliu** [comment]
@sorentwo Thanks for the quick reply.  I did `chmod 600 ~/.pgpass`, so I figured that's all I had to do, is there anything else that you know of?  That's all I got from here: http://www.postgresql.org/docs/current/static/libpq-pgpass.html

Also, the `.pgpass` file seems to be working when I try to connect through `psql` through the command line.

**Comment by sorentwo** [comment]
If I recall you can see the connection error printed in the Inspeqtor logs. What user are you running under? Is that user able to connect to psql?

**Comment by jmliu** [comment]
The user I'm running on is not the `root` user, but the user is able to connect through `psql` using the password in the `.pgpass` file.  The owner of the `.pgpass` file is the same user as well.  This is the error in the `inspeqtor.log`:

```
I 2016-05-12T16:51:21.554912Z 1309 Activating metrics for postgresql
Password for user <db_username>:
psql: fe_sendauth: no password supplied
```

Just to provide a bit more detail in case you'd like to recreate the issue, inspeqtor is running on an Amazon EC2 instance separate from the postgres db which is on an RDS instance.

**Comment by sorentwo** [comment]
Inspeqtor needs to run on the same server as postgres. Advanced metrics use a psql connection to extract stats, but all of the standard monitoring (cpu, memory) relies on the local postgres process.

In this situation you can simply use the alerts provided by AWS to notify you of events.

**Comment by jmliu** [comment]
Sounds good.  Thanks for the help. 👍
