### ISSUE TITLE
Ubuntu 16.04 not supported?

### ISSUE THREAD

**Issue by rocketblr** [mperham/inspeqtor#126]
Hi there,

I'm having issues with inspeqtor installation on ubuntu 16.04 64 bit:
Ubuntu-1604-xenial-64-minimal:~$ curl -L https://bit.ly/InspeqtorDEB | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   163  100   163    0     0    285      0 --:--:-- --:--:-- --:--:--   285
100   145    0   145    0     0     89      0 --:--:--  0:00:01 --:--:--   271
100  5200    0  5200    0     0   2869      0 --:--:--  0:00:01 --:--:--  2869
Detected operating system as Ubuntu/xenial.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/contribsys_inspeqtor.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
Ubuntu-1604-xenial-64-minimal:~$ sudo apt-get install inspeqtor
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package inspeqtor

**Comment by sorentwo** [comment]
No, at this point Ubuntu 16.04 isn't supported (we don't build a package for it). This is something we should work on adding as it is the new LTS release, it just isn't supported yet.

**Comment by sorentwo** [comment]
As a side note, you are welcome to try and pull down the 14.04 package, I think I recall others doing that for 14.14 or 15.x releases. There may be some instructions from @mperham if you search through the issues.

**Comment by mperham** [comment]
Just need a new line here:

https://github.com/mperham/inspeqtor/blob/master/Makefile#L163

**Comment by mperham** [comment]
Just pushed the initial work in #130.
