### ISSUE TITLE
Amazon Linux Support?

### ISSUE THREAD

**Issue by tonyhburns** [mperham/inspeqtor#129]
I see that CentOS is officially supported for Inspeqtor, and just wondering if that translates to Amazon Linux compatibility as well.

**Comment by mperham** [comment]
I've never tried Amazon Linux before but since it's a CentOS variant, I'd expect CentOS packages to install and work.  Run through the CentOS install directions and let us know if everything works?

**Comment by tonyhburns** [comment]
Will do! I'm currently evaluating Inspeqtor as an alternative to Monit in a new environment, so hoping it works well on Amazon Linux!
