### ISSUE TITLE
Add hostname to alert email

### ISSUE THREAD

**Issue by Zhomart** [mperham/inspeqtor#134]
Please add hostname to the alert emails. I run inspeqtor in multiple hosts, and it's hard to know which host had the problem.

**Comment by mperham** [comment]
Of course the alert emails include the host name. Please show us a bad email. I'd guess your machine is misconfiguured and Inspeqgor can't access the host name somehow.

**Comment by Zhomart** [comment]
Omg it includes hostname. I just named it inconveniently. Sorry for bothering,  closing the issue.
