### ISSUE TITLE
Installation does not work for Ubuntu 14.04

### ISSUE THREAD

**Issue by romanvbabenko** [mperham/inspeqtor#136]
Trying to install as it described in wiki for Ubuntu, but 

> sudo apt-get install inspeqtor
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package inspeqtor
```

> uname -a
```
Linux vagrant 3.19.0-56-generic #62-Ubuntu SMP Thu Mar 10 22:40:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mperham** [comment]
I don't know why it's not working for you. The DEB is here:

https://packagecloud.io/contribsys/inspeqtor/packages/ubuntu/trusty/inspeqtor_1.0.1-1_amd64.deb

**Comment by DragosIorgulescu** [comment]
I am bumping into the same issue, and checking available packages shows that this one does not exist: http://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=inspeqtor&searchon=names

Am I doing something wrong? @romanvbabenko were you able to figure it out?

**Comment by mperham** [comment]
My guess is that you don't have the packagecloud apt server in your sources.

https://github.com/mperham/inspeqtor/wiki/Installation

**Comment by sfoulston** [comment]
I'm running into this problem as well.

`uname -a`:
```
Linux ip-172-31-21-181 4.4.0-1034-aws #37-Ubuntu SMP Mon Nov 5 14:12:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

`/etc/apt/sources.list.d/contribsys_inspeqtor.list` looks like this:
```
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/contribsys/inspeqtor

deb https://packagecloud.io/contribsys/inspeqtor/ubuntu/ trusty main
deb-src https://packagecloud.io/contribsys/inspeqtor/ubuntu/ trusty main
```

But running `sudo apt-get update` I see these warnings:
```
W: Failed to fetch https://packagecloud.io/contribsys/inspeqtor/ubuntu/dists/trusty/main/source/Sources  HttpError429

W: Failed to fetch https://packagecloud.io/contribsys/inspeqtor/ubuntu/dists/trusty/main/binary-amd64/Packages  HttpError429
```

And `sudo apt-get install inspeqtor`:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package inspeqtor
```

Visting https://packagecloud.io/contribsys/inspeqtor/ubuntu/dists/trusty/ returns `429 Too Many Requests`.

**Comment by mperham** [comment]
Have you read the installation wiki page?

**Comment by sfoulston** [comment]
I was following the installation video at http://contribsys.com/inspeqtor/. Is the wiki indicating that I need to manually install the Upstart-compatible .deb at 
https://github.com/mperham/inspeqtor/releases/download/v2.0.0-1/inspeqtor_2.0.0-1_amd64.upstart.deb?

If so, would you mind helping with the necessary command to do that?

**Comment by sfoulston** [comment]
I'm still not having any luck with this. I've downloaded the .deb directly from the assets of the release in GitHub (as linked to from the installation wiki page), and I'm attempting to install it manually, but I'm getting errors however I try it.

`sudo apt install inspeqtor.deb`:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package inspeqtor.deb
E: Couldn't find any package by regex 'inspeqtor.deb'
```

`sudo dpkg -i inspeqtor.deb`:
```
dpkg-deb: error: `inspeqtor.deb' is not a debian format archive
dpkg: error processing archive inspeqtor.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 inspeqtor.deb
```

`sudo gdebi inspeqtor.deb`:
```
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Building data structures... Done 
Failed to open the software package
The package might be corrupted or you are not allowed to open the file. Check the permissions of the file.
```

Also tried the Quick Install script at https://packagecloud.io/contribsys/inspeqtor/install:

`curl -s https://packagecloud.io/install/repositories/contribsys/inspeqtor/script.deb.sh | sudo bash`:
```
Detected operating system as Ubuntu/trusty.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/contribsys_inspeqtor.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
```

`sudo apt-get install inspeqtor`:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package inspeqtor
```
