### ISSUE TITLE
Email alert says "than than" 

### ISSUE THREAD

**Issue by oree** [mperham/inspeqtor#137]
This is quite minor, but the alert email I get says something like

    swap is greater than than 20% for server

Apparently both the [email template](https://github.com/mperham/inspeqtor/blob/master/templates/email/RuleFailed.txt#L5) and the [rule operator](https://github.com/mperham/inspeqtor/blob/master/rules.go#L19) contain the word _than_.

I'm using inspeqtor version 1.0.1 on Ubuntu 16.04.

**Comment by mperham** [comment]
How weird that no one has noticed this before.
