### ISSUE TITLE
go get fails on Go 1.8

### ISSUE THREAD

**Issue by alanorth** [mperham/inspeqtor#138]
Trying to build locally with `go get` fails with Go 1.8 on macOS Sierra:

```console
$ go get github.com/mperham/inspeqtor
# github.com/mperham/inspeqtor
../../go/src/github.com/mperham/inspeqtor/actions.go:27: undefined: Asset
```

Go version:

```console
$ go version
go version go1.8 darwin/amd64
```

**Comment by mperham** [comment]
Inspeqtor is not go gettable. You have to build it with the Makefile as the Asset file has to be generated.

**Comment by alanorth** [comment]
Muchas gracias.

**Comment by mperham** [comment]
In case you didn't notice:

https://github.com/mperham/inspeqtor/wiki/Development
https://github.com/mperham/inspeqtor/wiki/Installation
