### ISSUE TITLE
Suggestions for monitoring systemd-exported foreman services?

### ISSUE THREAD

**Issue by pnomolos** [mperham/inspeqtor#140]
Foreman by default exports systemd services with a `@PORT` name - such as `service-name@5000`.  Do you have any suggestions on how to monitor since I believe (I'm not sure) that those port numbers are non-deterministic when the services are exported.

**Comment by mperham** [comment]
How could the ports be non-deterministic?  Don't you need to know the ports in order to hook up the services to each other, e.g. Redis on 6379, mysql on 3306, etc.

**Comment by pnomolos** [comment]
Sorry, incorrect terminology - not non-deterministic, but set at export time and are determined based on the contents of your Procfile.  From the docs:

    The $PORT value starts as the base port as specified by -p, then increments by 100 for 
    each new process line. Multiple instances of the same process are assigned $PORT 
    values that increment by 1.

In most cases you don't even care about the $PORT assigned to a given process.  For example, I have `helium-sidekiq@5400.service` but neither I nor sidekiq care about the port number because they're unused.  The problem ends up being that if the concurrency of a process is changed or the Procfile is re-ordered then all the port values change, which means the service names change.  While I can (and am) manually monitoring each service based on port number, you can see how this becomes a problem as soon as you start scaling, or try to have any sort of automation (ie, build a base image that has inspeqtor pre-configured for the services you are going to install later without knowing concurrency at that point).

Would asking for a "match service names" functionality be too much to ask, or would you suggest having a post-deployment task also generate the inspeqtor files (or perhaps just symlinking a base template).

**Comment by mperham** [comment]
You could fork this exporter to remove the PORT stuff and use it when exported or have it generate your .inq files at deploy time.

https://github.com/ddollar/foreman/blob/master/lib/foreman/export/systemd.rb

I don't want to match names because when you have two services, e.g. sidekiq-foo and sidekiq-bar, it's quite possible to select the wrong one.

**Comment by pnomolos** [comment]
@mperham OK, I'll look into doing that - I'll probably generate the .inq files at deploy time because the port number ends up being a unique identifier if you have a process with concurrency > 1.

My suggestion for matching would have been a slightly modified syntax - `check service /sidekiq-*/` - so it's very clear that you're explicitly matching names.

Does inspeqtor search subdirectories of /etc/inspeqtor/services.d for ".inq" files as well or just the top level?
