### ISSUE TITLE
Inspeqtor appears to lose track of running process (does not exist: no such process).

### ISSUE THREAD

**Issue by macgregordennis** [mperham/inspeqtor#141]
OS: Ubuntu 14.04
Upstart version: 1.12.1

I recently started using Inspeqtor to monitor some upstart-managed processes that have a memory leak issue that I haven’t yet been able to fix. Doing so has made the system more resilient, but sometimes this happens (process named redacted):

<img width="791" alt="screen shot 2017-06-18 at 1 24 38 am" src="https://user-images.githubusercontent.com/1322709/27323165-728982e8-5555-11e7-8ac5-a1830a7c9123.png">

According to the logs, everything seems to be going fine and then processes will no longer be found like so:

<img width="857" alt="screen shot 2017-06-18 at 1 27 01 am" src="https://user-images.githubusercontent.com/1322709/27323173-78cf3e90-5555-11e7-99d6-222bceec9f59.png">

If I then restart inspeqtor (i.e. sudo initctl restart inspeqtor) then inspeqtor can identify the processes and it operates correctly again. However, me having to ssh in and manually restart inspeqtor is not a good solution.

How can I handle this situation automatically? I’d like to either be able to automatically restart inspeqtor when such an alert is generated or fix the underlying issue.

**Comment by mperham** [comment]
It goes without saying that the whole point of process monitoring is to alert you when a process disappears.  Inspeqtor *should* handle this case; it's pretty common.

When a process crashes (I'm assuming the process SEGV's or something like that), Upstart will immediately note this and start a new process.  Inspeqtor will see that the PID no longer exists and query Upstart to gather the new PID.

https://github.com/mperham/inspeqtor/blob/ea2f3fa26f4e0e136ab26cb3bba2ba8421fdd3fb/types.go#L152
https://github.com/mperham/inspeqtor/blob/ea2f3fa26f4e0e136ab26cb3bba2ba8421fdd3fb/types.go#L164

It should fire an alert due to the change in PID but will immediately start monitoring that new PID for the service.  IOW the net result *should* be that you get an alert saying your service changed PIDs outside of a deploy.

All of this said, I can't explain why it's not working for you based on what you've posted.  Could you show your /etc/init/*.conf for the service so we can see how Upstart is controlling the service?

**Comment by macgregordennis** [comment]
> It goes without saying that the whole point of process monitoring is to alert you when a process disappears. Inspeqtor should handle this case; it's pretty common.

>When a process crashes (I'm assuming the process SEGV's or something like that), Upstart will immediately note this and start a new process. Inspeqtor will see that the PID no longer exists and query Upstart to gather the new PID.

Thanks for the explanation! The expected behavior does not appear to be happening, so the server is failing frequently from the memory leak (the servers are automatically replaced but this is still not great).

> It should fire an alert due to the change in PID but will immediately start monitoring that new PID for the service. IOW the net result should be that you get an alert saying your service changed PIDs outside of a deploy.

No alert message of this kind is being output.

> All of this said, I can't explain why it's not working for you based on what you've posted. Could you show your /etc/init/*.conf for the service so we can see how Upstart is controlling the service?

Ok, here's the conf file for one of the processes/services (process name replaced with process_name):

```
# config

description "Background worker"
# start on runlevel [2345]
# stop on runlevel [06]

# change to match your deployment user
setuid ubuntu
setgid ubuntu
env HOME=/home/ubuntu

# restart the process if it crashes
respawn
# respawn a max of 3 times within 30 seconds
respawn limit 3 30

# TERM is sent by sidekiqctl when stopping sidekiq.  Without declaring these as normal exit codes, it just respawns.
normal exit 0 TERM

script
# this script runs in /bin/sh by default
# respawn as bash so we can source in rbenv
exec /bin/bash <<'EOT'
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
  export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"

  cd /var/www/turing-email/current/
  exec bundle exec sidekiq -i 20 -e production -c 45 -q process_name
EOT
end script
```

Also, here's the inspeqtor configuration for the service:

```
check service process_name
  if memory:rss > 8000000 for 4 cycles then restart
  if cpu:total_system > 90% for 4 cycles then restart
```

Any thoughts on the above? It'd be great to this fixed. Right now, the logs show that inspeqtor starts fine and then starts losing track of processes and won't find them again unless restarted like so:

<img width="333" alt="screen shot 2017-06-22 at 10 28 25 pm" src="https://user-images.githubusercontent.com/1322709/27467794-3caeb61a-579a-11e7-9a31-f108ae7b315f.png">

**Comment by mperham** [comment]
Can you enable verbose logging in inspeqtor.conf and email me a private gist with the entire output once it loses Sidekiq?

Concurrency of 45 is pretty high for MRI, is Sidekiq stable for you at that value?
