### ISSUE TITLE
Monitoring Passenger when it's automatically started by nginx

### ISSUE THREAD

**Issue by smoyth** [mperham/inspeqtor#145]
I am not using standalone Passenger, rather the nginx version, which is much simpler to setup.

However, since nginx automatically starts it, there is no systemd service to track it. Also, Passenger's memory is not counted as part of nginx since it's a separate process.

Are there any easy ways to track Passenger in this setup? inspeqtor seems great and I'd love to be able to use it!

**Comment by smoyth** [comment]
Closed with no comment? Is that a 'no'?

**Comment by mperham** [comment]
I don't run Passenger so I don't know.  No one else commented.
