### ISSUE TITLE
packagecloud too many requests / Bandwidth or Storage Limit Exceeded

### ISSUE THREAD

**Issue by rclarkburns** [mperham/inspeqtor#153]
Hello,

I recently started to encounter the following using apt-get: 

```
W: Failed to fetch https://packagecloud.io/contribsys/inspeqtor/ubuntu/dists/bionic/InRelease  429  Too Many Requests
```

I also hit this trying to download from the browser: 

```
Bandwidth or Storage Limit Exceeded
```

Not sure if packagecloud imposes limits on open source projects. I can take up my issue with them if this is something that's not in your control. Thanks for your time. 

RCTID :)

**Comment by mperham** [comment]
Unfortunately we outgrew their free OSS plan and I forgot to update the Install page.  Fixed:

https://github.com/mperham/inspeqtor/wiki/Installation
