### ISSUE TITLE
INQ Configuration question

### ISSUE THREAD

**Issue by hopewise** [mperham/inspeqtor#160]
I am sorry that I am writing here, but I could not find a tag for `inspeqtor` at SO, however, I've created a tag there for your repo :) https://stackoverflow.com/questions/59624961/what-is-meant-by-cycle

I need to understand what is meant by cycle when it comes to INQ Configuration as below:

```
check service memcached
  if memory:rss > 1200m for 4 cycles then alert
  if cpu:user > 40% for 2 cycles then restart
```

Thanks

**Comment by mperham** [comment]
A cycle is the 15 or 30 second period between checks. I forget the cycle length.

**Comment by hopewise** [comment]
So, as for`if cpu:user > 40% for 2 cycles` it means if cpu > 40% for  2 x 30 seconds continuously then alert?  

How to set cycle to be 15 or 30 seconds?

**Comment by mperham** [comment]
cycle time is 15 seconds by default so it would be 2 x 15.

https://github.com/mperham/inspeqtor/wiki/Global-Configuration#miscellaneous
