### ISSUE TITLE
Failure to monitor upstart services in stopped state during Inspeqtor startup

### ISSUE THREAD

**Issue by felixbuenemann** [mperham/inspeqtor#73]
Inspeqtor 0.7.0-2 does not properly monitor upstart services that are in stopped state during inspeqtor startup. Instead the services are stuck in state `Unknown/0`, even if the monitored service is started later. It stays in this state until the inspeqtor service is reloaded using `reload inspeqtor`.

The expected behavior would be for the service to be in state `Down/0` and transitioning to `Up/$PID` when started.

This problem happens if the upstart service for inspeqtor starts earlier than the managed services.

Here's a shell session to show this behavior:

```bash
root@ubuntu:~# cat /etc/init/hello.conf
start on rc stopped
stop on shutdown

setuid nobody

script
  while /bin/true; do echo hello world; sleep 2 ; done
end script

root@ubuntu:~# cat /etc/inspeqtor/services.d/hello.inq
check service hello
  if memory:rss > 10m then restart

root@ubuntu:~# status hello
hello stop/waiting

root@ubuntu:~# inspeqtorctl status
Inspeqtor 0.7.0, uptime: 18.886962182s, pid: 9195
…
Service: hello [Unknown/0]
…

root@ubuntu:~# start hello
hello start/running, process 9499

root@ubuntu:~# inspeqtorctl status
Inspeqtor 0.7.0, uptime: 1m47.918169288s, pid: 9195
…
Service: hello [Unknown/0]
…

root@ubuntu:~# reload inspeqtor
root@ubuntu:~# inspeqtorctl status
Inspeqtor 0.7.0, uptime: 8.128170701s, pid: 9195
…
Service: hello [Up/9499]
…

root@ubuntu:~# stop hello
hello stop/waiting
root@ubuntu:~# inspeqtorctl status
Inspeqtor 0.7.0, uptime: 1m32.401469022s, pid: 9195
…
Service: hello [Down/0]
…
```

**Comment by felixbuenemann** [comment]
:tada: Happy New Year, Mike! :four_leaf_clover:

**Comment by mperham** [comment]
:tada: :cake: I think I fell asleep at 9:30pm last night!   :+1:
