### ISSUE TITLE
Release 0.8.0

### ISSUE THREAD

**Issue by mperham** [mperham/inspeqtor#75]
Current master is the 0.8.0 candidate.  I'll release it tomorrow unless anyone has objections.

* [x] Update changelog
* [x] Update wiki
* [x] Write blog post

**Comment by sorentwo** [comment]
I'm looking forward to it. No objections here.

**Comment by sorentwo** [comment]
Installed on staging `Setting up inspeqtor (0.8.0-1)`. Unfortunately it hasn't fixed my issue of emailing that a `pid` has been lost every time Sidekiq restarts. I'll dig that at the beginning of next week.
