### ISSUE TITLE
Error building for OSX 10.10.1

### ISSUE THREAD

**Issue by johntdyer** [mperham/inspeqtor#77]
#### Environment

* osx 10.10.1
* Go 1.4.0

I followed the steps outlined [here](https://github.com/mperham/inspeqtor/wiki/Development) and I get the following error:

```log
$ make                                                                                        (master⚡)
# github.com/mperham/inspeqtor
../../../../.gvm/pkgsets/go1.4/global/src/github.com/mperham/inspeqtor/actions.go:27: undefined: Asset
ok  	_/Users/jdyer/src/github.com/mperham/inspeqtor	0.032s
```

**Comment by mperham** [comment]
The Assets are generated in the `test` Makefile target by `go generate`.  For some reason it isn't working for you.

**Comment by johntdyer** [comment]
ok...  is there any reason you can think of why this would be happening?

**Comment by mperham** [comment]
Hmm, run the command yourself manually: `go-bindata -pkg inspeqtor -o templates.go templates/...`  Does it create templates.go with the Asset function?

**Comment by johntdyer** [comment]
@mperham I got further that time

```
$ make                                                                                                                                                                                                                 (master⚡)
ok  	github.com/mperham/inspeqtor	0.028s
ok  	github.com/mperham/inspeqtor/conf/global	0.021s
ok  	github.com/mperham/inspeqtor/conf/inq	0.012s
ok  	github.com/mperham/inspeqtor/metrics	0.025s
2015/01/24 11:35:37 W 2015-01-24T16:35:37.680812Z 66334 Could not find metric mysql(Connections), did you spell it right?
2015/01/24 11:35:37 W 2015-01-24T16:35:37.680931Z 66334 Could not find metric mysql(Queries), did you spell it right?
2015/01/24 11:35:37 W 2015-01-24T16:35:37.680939Z 66334 Could not find metric mysql(Table_locks_waited), did you spell it right?
--- FAIL: TestRealMysqlConnection (0.00s)
        Location:       mysql_test.go:59
	Error:		Should be true

        Location:       mysql_test.go:69
	Error:		Should be true
	Messages:	This test will fail if you don't have mysql installed

map[]2015/01/24 11:35:37 W 2015-01-24T16:35:37.683775Z 66334 Could not find metric mysql(bad_metric), did you spell it right?
--- FAIL: TestRealPostgresqlConnection (0.00s)
        Location:       postgresql_test.go:54
	Error:		Expected nil, but got: &errors.errorString{s:""}

        Location:       postgresql_test.go:56
	Error:		Expected nil, but got: &errors.errorString{s:""}

        Location:       postgresql_test.go:57
	Error:		Expected not to be nil.

        Location:       postgresql_test.go:61
	Error:		Should be true
	Messages:	This test will fail if you don't have postgresql installed

2015/01/24 11:35:37 W 2015-01-24T16:35:37.685268Z 66334 Could not find metric redis(bad_metric), did you spell it right?
2015/01/24 11:35:37 W 2015-01-24T16:35:37.685443Z 66334 Could not find metric redis(latest_fork_usec), did you spell it right?
2015/01/24 11:35:37 W 2015-01-24T16:35:37.685452Z 66334 Could not find metric redis(connected_clients), did you spell it right?
2015/01/24 11:35:37 W 2015-01-24T16:35:37.685456Z 66334 Could not find metric redis(master_repl_offset), did you spell it right?
--- FAIL: TestRealRedisConnection (0.00s)
        Location:       redis_test.go:54
	Error:		Should be true
	Messages:	This test will fail if you don't have redis-cli installed

--- FAIL: TestRealNginxConnection (0.01s)
        Location:       nginx_test.go:47
	Error:		Expected nil, but got: &url.Error{Op:"Get", URL:"http://localhost:8080/status", Err:(*net.OpError)(0xc20803afc0)}

        Location:       nginx_test.go:48
	Error:		Expected not to be nil.

        Location:       nginx_test.go:52
	Error:		Should be true
	Messages:	This test will fail if you don't have nginx installed

--- FAIL: TestRealMemcachedConnection (0.01s)
        Location:       memcached_test.go:44
	Error:		Expected nil, but got: &exec.ExitError{ProcessState:(*os.ProcessState)(0xc2080941a0)}

        Location:       memcached_test.go:45
	Error:		Expected not to be nil.

        Location:       memcached_test.go:47
	Error:		Should be true
	Messages:	This test will fail if you don't have memcached installed

FAIL
FAIL	github.com/mperham/inspeqtor/metrics/daemon	0.020s
--- FAIL: TestLaunchd (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x6d1bd]

goroutine 7 [running]:
testing.func·006()
	/Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:441 +0x181
github.com/mperham/inspeqtor/services.TestLaunchd(0xc20806a120)
	/Users/jdyer/.gvm/pkgsets/go1.4/global/src/github.com/mperham/inspeqtor/services/launchd_test.go:36 +0x95d
testing.tRunner(0xc20806a120, 0x4b62d8)
	/Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
testing.RunTests(0x3c1fc0, 0x4b62c0, 0x8, 0x8, 0x4b9b01)
	/Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:576 +0x58e
testing.(*M).Run(0xc2080522d0, 0x4c0f20)
	/Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:485 +0x6c
main.main()
	github.com/mperham/inspeqtor/services/_test/_testmain.go:66 +0x1d5

goroutine 8 [chan receive]:
testing.func·007()
	/Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:559 +0x5f
created by testing.RunTests
	/Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:560 +0xb9b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/Users/jdyer/.gvm/gos/go1.4/src/runtime/asm_amd64.s:2232 +0x1
FAIL	github.com/mperham/inspeqtor/services	0.027s
ok  	github.com/mperham/inspeqtor/util	0.022s

# jdyer at retina.dyer in ~/.gvm/pkgsets/go1.4/global/src/github.com/mperham/inspeqtor on git:master o [11:35:38]
$                                                                                                                                                                                                                      (master⚡)
```

**Comment by mperham** [comment]
I'll look at the tests on Monday. You can run the build steps manually to bypass the tests.


> On Jan 24, 2015, at 08:36, John Dyer <notifications@github.com> wrote:
> 
> @mperham I got further that time
> 
> $ make                                                                                                                                                                                                                 (master⚡)
> ok      github.com/mperham/inspeqtor    0.028s
> ok      github.com/mperham/inspeqtor/conf/global    0.021s
> ok      github.com/mperham/inspeqtor/conf/inq   0.012s
> ok      github.com/mperham/inspeqtor/metrics    0.025s
> 2015/01/24 11:35:37 W 2015-01-24T16:35:37.680812Z 66334 Could not find metric mysql(Connections), did you spell it right?
> 2015/01/24 11:35:37 W 2015-01-24T16:35:37.680931Z 66334 Could not find metric mysql(Queries), did you spell it right?
> 2015/01/24 11:35:37 W 2015-01-24T16:35:37.680939Z 66334 Could not find metric mysql(Table_locks_waited), did you spell it right?
> --- FAIL: TestRealMysqlConnection (0.00s)
>         Location:       mysql_test.go:59
>     Error:      Should be true
> 
>         Location:       mysql_test.go:69
>     Error:      Should be true
>     Messages:   This test will fail if you don't have mysql installed
> 
> map[]2015/01/24 11:35:37 W 2015-01-24T16:35:37.683775Z 66334 Could not find metric mysql(bad_metric), did you spell it right?
> --- FAIL: TestRealPostgresqlConnection (0.00s)
>         Location:       postgresql_test.go:54
>     Error:      Expected nil, but got: &errors.errorString{s:""}
> 
>         Location:       postgresql_test.go:56
>     Error:      Expected nil, but got: &errors.errorString{s:""}
> 
>         Location:       postgresql_test.go:57
>     Error:      Expected not to be nil.
> 
>         Location:       postgresql_test.go:61
>     Error:      Should be true
>     Messages:   This test will fail if you don't have postgresql installed
> 
> 2015/01/24 11:35:37 W 2015-01-24T16:35:37.685268Z 66334 Could not find metric redis(bad_metric), did you spell it right?
> 2015/01/24 11:35:37 W 2015-01-24T16:35:37.685443Z 66334 Could not find metric redis(latest_fork_usec), did you spell it right?
> 2015/01/24 11:35:37 W 2015-01-24T16:35:37.685452Z 66334 Could not find metric redis(connected_clients), did you spell it right?
> 2015/01/24 11:35:37 W 2015-01-24T16:35:37.685456Z 66334 Could not find metric redis(master_repl_offset), did you spell it right?
> --- FAIL: TestRealRedisConnection (0.00s)
>         Location:       redis_test.go:54
>     Error:      Should be true
>     Messages:   This test will fail if you don't have redis-cli installed
> 
> --- FAIL: TestRealNginxConnection (0.01s)
>         Location:       nginx_test.go:47
>     Error:      Expected nil, but got: &url.Error{Op:"Get", URL:"http://localhost:8080/status", Err:(*net.OpError)(0xc20803afc0)}
> 
>         Location:       nginx_test.go:48
>     Error:      Expected not to be nil.
> 
>         Location:       nginx_test.go:52
>     Error:      Should be true
>     Messages:   This test will fail if you don't have nginx installed
> 
> --- FAIL: TestRealMemcachedConnection (0.01s)
>         Location:       memcached_test.go:44
>     Error:      Expected nil, but got: &exec.ExitError{ProcessState:(*os.ProcessState)(0xc2080941a0)}
> 
>         Location:       memcached_test.go:45
>     Error:      Expected not to be nil.
> 
>         Location:       memcached_test.go:47
>     Error:      Should be true
>     Messages:   This test will fail if you don't have memcached installed
> 
> FAIL
> FAIL    github.com/mperham/inspeqtor/metrics/daemon 0.020s
> --- FAIL: TestLaunchd (0.01s)
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
>     panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xb code=0x1 addr=0x0 pc=0x6d1bd]
> 
> goroutine 7 [running]:
> testing.func·006()
>     /Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:441 +0x181
> github.com/mperham/inspeqtor/services.TestLaunchd(0xc20806a120)
>     /Users/jdyer/.gvm/pkgsets/go1.4/global/src/github.com/mperham/inspeqtor/services/launchd_test.go:36 +0x95d
> testing.tRunner(0xc20806a120, 0x4b62d8)
>     /Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:447 +0xbf
> created by testing.RunTests
>     /Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:555 +0xa8b
> 
> goroutine 1 [chan receive]:
> testing.RunTests(0x3c1fc0, 0x4b62c0, 0x8, 0x8, 0x4b9b01)
>     /Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:576 +0x58e
> testing.(*M).Run(0xc2080522d0, 0x4c0f20)
>     /Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:485 +0x6c
> main.main()
>     github.com/mperham/inspeqtor/services/_test/_testmain.go:66 +0x1d5
> 
> goroutine 8 [chan receive]:
> testing.func·007()
>     /Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:559 +0x5f
> created by testing.RunTests
>     /Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:560 +0xb9b
> 
> goroutine 17 [syscall, locked to thread]:
> runtime.goexit()
>     /Users/jdyer/.gvm/gos/go1.4/src/runtime/asm_amd64.s:2232 +0x1
> FAIL    github.com/mperham/inspeqtor/services   0.027s
> ok      github.com/mperham/inspeqtor/util   0.022s
> 
> # jdyer at retina.dyer in ~/.gvm/pkgsets/go1.4/global/src/github.com/mperham/inspeqtor on git:master o [11:35:38]
> $                                                                                                                                                                                                                      (master⚡)
> —
> Reply to this email directly or view it on GitHub.
>

**Comment by mperham** [comment]
I just pushed a fix which will tell us why launchd_test is failing on your
machine.

On Sat, Jan 24, 2015 at 8:36 AM, John Dyer <notifications@github.com> wrote:

> @mperham <https://github.com/mperham> I got further that time
>
> $ make                                                                                                                                                                                                                 (master⚡)
> ok      github.com/mperham/inspeqtor    0.028s
> ok      github.com/mperham/inspeqtor/conf/global    0.021s
> ok      github.com/mperham/inspeqtor/conf/inq   0.012s
> ok      github.com/mperham/inspeqtor/metrics    0.025s
> 2015/01/24 11:35:37 W 2015-01-24T16:35:37.680812Z 66334 Could not find metric mysql(Connections), did you spell it right?
> 2015/01/24 11:35:37 W 2015-01-24T16:35:37.680931Z 66334 Could not find metric mysql(Queries), did you spell it right?
> 2015/01/24 11:35:37 W 2015-01-24T16:35:37.680939Z 66334 Could not find metric mysql(Table_locks_waited), did you spell it right?
> --- FAIL: TestRealMysqlConnection (0.00s)
>         Location:       mysql_test.go:59
>     Error:      Should be true
>
>         Location:       mysql_test.go:69
>     Error:      Should be true
>     Messages:   This test will fail if you don't have mysql installed
>
> map[]2015/01/24 11:35:37 W 2015-01-24T16:35:37.683775Z 66334 Could not find metric mysql(bad_metric), did you spell it right?
> --- FAIL: TestRealPostgresqlConnection (0.00s)
>         Location:       postgresql_test.go:54
>     Error:      Expected nil, but got: &errors.errorString{s:""}
>
>         Location:       postgresql_test.go:56
>     Error:      Expected nil, but got: &errors.errorString{s:""}
>
>         Location:       postgresql_test.go:57
>     Error:      Expected not to be nil.
>
>         Location:       postgresql_test.go:61
>     Error:      Should be true
>     Messages:   This test will fail if you don't have postgresql installed
>
> 2015/01/24 11:35:37 W 2015-01-24T16:35:37.685268Z 66334 Could not find metric redis(bad_metric), did you spell it right?
> 2015/01/24 11:35:37 W 2015-01-24T16:35:37.685443Z 66334 Could not find metric redis(latest_fork_usec), did you spell it right?
> 2015/01/24 11:35:37 W 2015-01-24T16:35:37.685452Z 66334 Could not find metric redis(connected_clients), did you spell it right?
> 2015/01/24 11:35:37 W 2015-01-24T16:35:37.685456Z 66334 Could not find metric redis(master_repl_offset), did you spell it right?
> --- FAIL: TestRealRedisConnection (0.00s)
>         Location:       redis_test.go:54
>     Error:      Should be true
>     Messages:   This test will fail if you don't have redis-cli installed
>
> --- FAIL: TestRealNginxConnection (0.01s)
>         Location:       nginx_test.go:47
>     Error:      Expected nil, but got: &url.Error{Op:"Get", URL:"http://localhost:8080/status", Err:(*net.OpError)(0xc20803afc0)}
>
>         Location:       nginx_test.go:48
>     Error:      Expected not to be nil.
>
>         Location:       nginx_test.go:52
>     Error:      Should be true
>     Messages:   This test will fail if you don't have nginx installed
>
> --- FAIL: TestRealMemcachedConnection (0.01s)
>         Location:       memcached_test.go:44
>     Error:      Expected nil, but got: &exec.ExitError{ProcessState:(*os.ProcessState)(0xc2080941a0)}
>
>         Location:       memcached_test.go:45
>     Error:      Expected not to be nil.
>
>         Location:       memcached_test.go:47
>     Error:      Should be true
>     Messages:   This test will fail if you don't have memcached installed
>
> FAIL
> FAIL    github.com/mperham/inspeqtor/metrics/daemon 0.020s
> --- FAIL: TestLaunchd (0.01s)
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
>     panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xb code=0x1 addr=0x0 pc=0x6d1bd]
>
> goroutine 7 [running]:
> testing.func·006()
>     /Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:441 +0x181github.com/mperham/inspeqtor/services.TestLaunchd(0xc20806a120)
>     /Users/jdyer/.gvm/pkgsets/go1.4/global/src/github.com/mperham/inspeqtor/services/launchd_test.go:36 +0x95d
> testing.tRunner(0xc20806a120, 0x4b62d8)
>     /Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:447 +0xbf
> created by testing.RunTests
>     /Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:555 +0xa8b
>
> goroutine 1 [chan receive]:
> testing.RunTests(0x3c1fc0, 0x4b62c0, 0x8, 0x8, 0x4b9b01)
>     /Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:576 +0x58e
> testing.(*M).Run(0xc2080522d0, 0x4c0f20)
>     /Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:485 +0x6c
> main.main()
>     github.com/mperham/inspeqtor/services/_test/_testmain.go:66 +0x1d5
>
> goroutine 8 [chan receive]:
> testing.func·007()
>     /Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:559 +0x5f
> created by testing.RunTests
>     /Users/jdyer/.gvm/gos/go1.4/src/testing/testing.go:560 +0xb9b
>
> goroutine 17 [syscall, locked to thread]:
> runtime.goexit()
>     /Users/jdyer/.gvm/gos/go1.4/src/runtime/asm_amd64.s:2232 +0x1
> FAIL    github.com/mperham/inspeqtor/services   0.027s
> ok      github.com/mperham/inspeqtor/util   0.022s
>
> # jdyer at retina.dyer in ~/.gvm/pkgsets/go1.4/global/src/github.com/mperham/inspeqtor on git:master o [11:35:38]
> $                                                                                                                                                                                                                      (master⚡)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mperham/inspeqtor/issues/77#issuecomment-71325812>.
>

**Comment by johntdyer** [comment]
Thanks for looking more into this.. I checked out master ( 80efd77f2f540ee008408b017fdba4e8394720d1 ) and here is where I stand right now:


### make prepare
```
# jdyer at retina.dyer in ~/.gvm/pkgsets/go1.4/global/src/github.com/mperham/inspeqtor on git:master o [10:18:42]
$ make prepare
#wget https://storage.googleapis.com/golang/go1.3.3.linux-amd64.tar.gz
#sudo tar -C /usr/local -xzf go1.3.3.linux-amd64.tar.gz
go get github.com/stretchr/testify/...
go get github.com/jteeuwen/go-bindata/...
go get code.google.com/p/gocc/...
# needed for `make fmt`
go get golang.org/x/tools/cmd/goimports
Now you should be ready to run make
# To cross-compile from OSX to Linux, you need to run this:
# cd OROOT/src && GOOS=linux GOARCH=amd64 CGO_ENABLED=0 ./make.bash --no-clean
```

### make 
```
# jdyer at retina.dyer in ~/.gvm/pkgsets/go1.4/global/src/github.com/mperham/inspeqtor on git:master o [10:18:46]
$ make                                                                                                                                                                                                                 (master⚡)
ok  	github.com/mperham/inspeqtor	0.028s
ok  	github.com/mperham/inspeqtor/conf/global	0.013s
ok  	github.com/mperham/inspeqtor/conf/inq	0.012s
ok  	github.com/mperham/inspeqtor/metrics	0.028s
2015/01/25 10:18:49 W 2015-01-25T15:18:49.495932Z 72488 Could not find metric mysql(Connections), did you spell it right?
2015/01/25 10:18:49 W 2015-01-25T15:18:49.496049Z 72488 Could not find metric mysql(Queries), did you spell it right?
2015/01/25 10:18:49 W 2015-01-25T15:18:49.496057Z 72488 Could not find metric mysql(Table_locks_waited), did you spell it right?
--- FAIL: TestRealMysqlConnection (0.00s)
        Location:       mysql_test.go:59
	Error:		Should be true

        Location:       mysql_test.go:69
	Error:		Should be true
	Messages:	This test will fail if you don't have mysql installed

2015/01/25 10:18:49 W 2015-01-25T15:18:49.498284Z 72488 Could not find metric mysql(bad_metric), did you spell it right?
map[]--- FAIL: TestRealPostgresqlConnection (0.00s)
        Location:       postgresql_test.go:54
	Error:		Expected nil, but got: &errors.errorString{s:""}

        Location:       postgresql_test.go:56
	Error:		Expected nil, but got: &errors.errorString{s:""}

        Location:       postgresql_test.go:57
	Error:		Expected not to be nil.

        Location:       postgresql_test.go:61
	Error:		Should be true
	Messages:	This test will fail if you don't have postgresql installed

2015/01/25 10:18:49 W 2015-01-25T15:18:49.501999Z 72488 Could not find metric redis(bad_metric), did you spell it right?
--- FAIL: TestRealNginxConnection (0.01s)
        Location:       nginx_test.go:47
	Error:		Expected nil, but got: &url.Error{Op:"Get", URL:"http://localhost:8080/status", Err:(*net.OpError)(0xc20803a980)}

        Location:       nginx_test.go:48
	Error:		Expected not to be nil.

        Location:       nginx_test.go:52
	Error:		Should be true
	Messages:	This test will fail if you don't have nginx installed

2015/01/25 10:18:49 W 2015-01-25T15:18:49.502209Z 72488 Could not find metric redis(connected_clients), did you spell it right?
2015/01/25 10:18:49 W 2015-01-25T15:18:49.502222Z 72488 Could not find metric redis(master_repl_offset), did you spell it right?
2015/01/25 10:18:49 W 2015-01-25T15:18:49.502230Z 72488 Could not find metric redis(latest_fork_usec), did you spell it right?
--- FAIL: TestRealRedisConnection (0.00s)
        Location:       redis_test.go:54
	Error:		Should be true
	Messages:	This test will fail if you don't have redis-cli installed

--- FAIL: TestRealMemcachedConnection (0.01s)
        Location:       memcached_test.go:44
	Error:		Expected nil, but got: &exec.ExitError{ProcessState:(*os.ProcessState)(0xc20809b560)}

        Location:       memcached_test.go:45
	Error:		Expected not to be nil.

        Location:       memcached_test.go:47
	Error:		Should be true
	Messages:	This test will fail if you don't have memcached installed

FAIL
FAIL	github.com/mperham/inspeqtor/metrics/daemon	0.021s
--- FAIL: TestLaunchd (0.02s)
        Location:       launchd_test.go:36
	Error:		Expected nil, but got: &services.ServiceError{Init:"launchd", Name:"homebrew.mxcl.memcached", Err:(*errors.errorString)(0xc20802a9b0)}

FAIL
FAIL	github.com/mperham/inspeqtor/services	0.033s
ok  	github.com/mperham/inspeqtor/util	0.025s
```

I did notice the exit code is actually 0, so I am not 100% sure if the tests are in fact failing 
# jdyer at retina.dyer in ~/.gvm/pkgsets/go1.4/global/src/github.com/mperham/inspeqtor on git:master o [10:18:49]
$ echo $?                                                                                                                                                                                                              
0
```

**Comment by mperham** [comment]
Son of a beach.  Your problem is right here:

```
--- FAIL: TestLaunchd (0.02s)
        Location:       launchd_test.go:36
    Error:      Expected nil, but got: &services.ServiceError{Init:"launchd", Name:"homebrew.mxcl.memcached", Err:(*errors.errorString)(0xc20802a9b0)}
```

But of course Go isn't printing out the actual error message.  Can you print the error on `services/launchd_test.go:36` so I can figure out how to fix it?

**Comment by johntdyer** [comment]
Here you go

```
FAIL	github.com/mperham/inspeqtor/metrics/daemon	0.020s
(0x56e258,0xc2080ad770)--- FAIL: TestLaunchd (0.03s)
        Location:       launchd_test.go:39
	Error:		Expected nil, but got: &services.ServiceError{Init:"launchd", Name:"homebrew.mxcl.memcached", Err:(*errors.errorString)(0xc20802a9b0)}

FAIL
FAIL	github.com/mperham/inspeqtor/services	0.039s
ok  	github.com/mperham/inspeqtor/util	0.025s

```

**Comment by mperham** [comment]
Sorry, that's not giving me the info I need.  Can you add this fmt line in launchd_test.go?

```go
st1, err := l.LookupService("homebrew.mxcl.memcached")
fmt.Println(err.Error())
assert.Nil(t, err)
```

**Comment by johntdyer** [comment]
sure, here you go 

```go
package services

import (
	"fmt"
	"github.com/mperham/inspeqtor/util"
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestLaunchd(t *testing.T) {
	if !util.Darwin() {
		t.Skip("FIXME - OSX only")
		return
	}
	t.Parallel()
	l, err := detectLaunchd("darwin/")
	assert.Nil(t, err)
	assert.NotNil(t, l)

	// Verify we can find a known good service.
	// Should be running on all OSX machines, right?
	st, err := l.LookupService("com.apple.Finder")
	assert.NotNil(t, st)
	assert.Nil(t, err)
	assert.True(t, st.Pid > 0, "Expected positive value for PID")
	assert.Equal(t, Up, st.Status)

	st, err = l.LookupService("some.fake.service")
	assert.Nil(t, st)
	assert.NotNil(t, err)

	err = l.Restart("some.jacked.up.name")
	assert.NotNil(t, err)

	st1, err := l.LookupService("homebrew.mxcl.memcached")
	if err != nil {
		fmt.Println(err.Error())

	}
	assert.Nil(t, err)

	if err == nil && st1.Pid > 0 && st1.Status == Up {
		err = l.Restart("homebrew.mxcl.memcached")
		assert.Nil(t, err)
		st2, err := l.LookupService("homebrew.mxcl.memcached")
		assert.Nil(t, err)
		assert.Equal(t, Up, st2.Status)
		assert.NotEqual(t, st1.Pid, st2.Pid)
	}
}

```

```log
$                                                                                                                                                                                                                      (master⚡)

# jdyer at retina.dyer in ~/.gvm/pkgsets/go1.4/global/src/github.com/mperham/inspeqtor on git:master x [13:06:20]
$ make                                                                                                                                                                                                                 (master⚡)
ok  	github.com/mperham/inspeqtor	0.027s
ok  	github.com/mperham/inspeqtor/conf/global	0.012s
ok  	github.com/mperham/inspeqtor/conf/inq	0.012s
ok  	github.com/mperham/inspeqtor/metrics	0.027s
2015/01/26 13:06:22 W 2015-01-26T18:06:22.157315Z 19009 Could not find metric mysql(bad_metric), did you spell it right?
2015/01/26 13:06:22 W 2015-01-26T18:06:22.157887Z 19009 Could not find metric mysql(Table_locks_waited), did you spell it right?
2015/01/26 13:06:22 W 2015-01-26T18:06:22.157902Z 19009 Could not find metric mysql(Connections), did you spell it right?
2015/01/26 13:06:22 W 2015-01-26T18:06:22.157909Z 19009 Could not find metric mysql(Queries), did you spell it right?
--- FAIL: TestRealMysqlConnection (0.00s)
        Location:       mysql_test.go:59
	Error:		Should be true

        Location:       mysql_test.go:69
	Error:		Should be true
	Messages:	This test will fail if you don't have mysql installed

map[]--- FAIL: TestRealPostgresqlConnection (0.00s)
        Location:       postgresql_test.go:54
	Error:		Expected nil, but got: &errors.errorString{s:""}

        Location:       postgresql_test.go:56
	Error:		Expected nil, but got: &errors.errorString{s:""}

        Location:       postgresql_test.go:57
	Error:		Expected not to be nil.

        Location:       postgresql_test.go:61
	Error:		Should be true
	Messages:	This test will fail if you don't have postgresql installed

2015/01/26 13:06:22 W 2015-01-26T18:06:22.161189Z 19009 Could not find metric redis(bad_metric), did you spell it right?
2015/01/26 13:06:22 W 2015-01-26T18:06:22.161568Z 19009 Could not find metric redis(latest_fork_usec), did you spell it right?
2015/01/26 13:06:22 W 2015-01-26T18:06:22.161582Z 19009 Could not find metric redis(connected_clients), did you spell it right?
2015/01/26 13:06:22 W 2015-01-26T18:06:22.161589Z 19009 Could not find metric redis(master_repl_offset), did you spell it right?
--- FAIL: TestRealRedisConnection (0.00s)
        Location:       redis_test.go:54
	Error:		Should be true
	Messages:	This test will fail if you don't have redis-cli installed

--- FAIL: TestRealNginxConnection (0.00s)
        Location:       nginx_test.go:47
	Error:		Expected nil, but got: &url.Error{Op:"Get", URL:"http://localhost:8080/status", Err:(*net.OpError)(0xc20803a7c0)}

        Location:       nginx_test.go:48
	Error:		Expected not to be nil.

        Location:       nginx_test.go:52
	Error:		Should be true
	Messages:	This test will fail if you don't have nginx installed

--- FAIL: TestRealMemcachedConnection (0.01s)
        Location:       memcached_test.go:44
	Error:		Expected nil, but got: &exec.ExitError{ProcessState:(*os.ProcessState)(0xc20809c3e0)}

        Location:       memcached_test.go:45
	Error:		Expected not to be nil.

        Location:       memcached_test.go:47
	Error:		Should be true
	Messages:	This test will fail if you don't have memcached installed

FAIL
FAIL	github.com/mperham/inspeqtor/metrics/daemon	0.021s
launchd/homebrew.mxcl.memcached: No such service
--- FAIL: TestLaunchd (0.01s)
        Location:       launchd_test.go:40
	Error:		Expected nil, but got: &services.ServiceError{Init:"launchd", Name:"homebrew.mxcl.memcached", Err:(*errors.errorString)(0xc20802a9b0)}

FAIL
FAIL	github.com/mperham/inspeqtor/services	0.025s
ok  	github.com/mperham/inspeqtor/util	0.024s

# jdyer at retina.dyer in ~/.gvm/pkgsets/go1.4/global/src/github.com/mperham/inspeqtor on git:master x [13:06:22]
$                                                                                                                                                                                                                      (master⚡)
```

**Comment by mperham** [comment]
Ok, thanks, fixed on master.  The test was assuming you had Homebrew memcached installed.  :-1:

**Comment by johntdyer** [comment]
Thanks, so after running `make` should I be expecting a binary anywhere?

**Comment by mperham** [comment]
"Make build" should get you an inspeqtor binary in the root dir.
