### ISSUE TITLE
Add support to configure smtp port?

### ISSUE THREAD

**Issue by exploid** [mperham/inspeqtor#78]
I understand that you don't want to enable plaintext SMTP usage over the network as per #24. While I agree with this, I'm trying to configure the port to something other than 587 while continuing to use TLS.

Google Compute Engine does [not allow outbound connections](https://cloud.google.com/compute/docs/sending-mail) on ports 25, 465, and 587. SendGrid alternatively supports port 2525 with TLS for that reason.

I would prefer to configure Inspeqtor to use port 2525 instead of having to configure postfix on my instances.

Would you be interested in a pull request that adds an smtp option to specify the port?

**Comment by mperham** [comment]
Maybe a tls_port option?  I'd be down with that.

**Comment by sorentwo** [comment]
This seems entirely sane to me.

**Comment by mperham** [comment]
When I think smtp_port, I think plaintext port 25.  Is tls_port the right name?

**Comment by exploid** [comment]
#78
