### ISSUE TITLE
inspeqtorctl requires sudo

### ISSUE THREAD

**Issue by threadhead** [mperham/inspeqtor#81]
`inspeqtorctl` did not require sudo for execution a few days ago. I admit that I didn't dig much to explore the cause. But on deploy today, I now see this:

    deploy@scoutz:/usr/bin$ inspeqtorctl start deploy
    nc: unix connect failed: Permission denied

    # let's restart inspector for giggles
    deploy@scoutz:/usr/bin$ sudo initctl restart inspeqtor
    inspeqtor start/running, process 1009
    deploy@scoutz:/usr/bin$ inspeqtorctl start deploy
    nc: unix connect failed: Permission denied

    # but
    deploy@scoutz:/usr/bin$ sudo inspeqtorctl start deploy
    Starting deploy, now silenced

I thought this was fixed in [#27](https://github.com/mperham/inspeqtor/issues/27). Using:

    deploy@scoutz:/usr/bin$ inspeqtor --version
    Inspeqtor 0.8.1
    Copyright © 2015 Contributed Systems LLC
    Licensed under the GNU Public License 3.0
    ...

**Comment by sorentwo** [comment]
@threadhead: Is the `deploy` user a member of the `adm` group? #27 references 4eb0071a5, which notes that sudo is not needed so long as the user interacting with `inspeqtorctl` is in the `adm` group.

**Comment by newdark** [comment]
I found that the only way to get access to inspeqtor on Centos 6 was to make the command available to the user using something like this.

http://www.atrixnet.com/allow-an-unprivileged-user-to-run-a-certain-command-with-sudo/

It is a pain but because of the way that server is setup inspeqtor will only run as a under sudo access. If you go to another OS it can get you around the problem but this is not something that is really under the control of the inpeqtor tool.

**Comment by threadhead** [comment]
@sorentwo tried that, did not work.

    sudo usermod -a -G adm deploy
    [sudo] password for deploy: 
    deploy@scoutz:~$ groups deploy
    deploy : deploy adm

    deploy@scoutz:~$ inspeqtorctl start deploy
    nc: unix connect failed: Permission denied

Again, this was working only a few days ago. And it works on staging server, which is probably 95% same as production.

**Comment by mperham** [comment]
What are the permissions on `/var/run/inspeqtor.sock`?

**Comment by threadhead** [comment]
@mperham 

    deploy@scoutz:~$ ls /var/run/inspeqtor.sock 
    srwxrwxr-x 1 root 0 Feb 19 10:12 /var/run/inspeqtor.sock=

**Comment by threadhead** [comment]
@mperham, better:

    deploy@scoutz:~$ \ls -l /var/run/inspeqtor.sock 
    srwxrwxr-x 1 root adm 0 Feb 19 10:12 /var/run/inspeqtor.sock

**Comment by mperham** [comment]
You need to re-login for group permissions to update, I think.

**Comment by threadhead** [comment]
Bada-bing, re-login:

    deploy@scoutz:~$ inspeqtorctl start deploy
    Starting deploy, now silenced

Thank you.
