### ISSUE TITLE
inspeqtorctl finish deploy notifiying that sidekiq process is running

### ISSUE THREAD

**Issue by newdark** [mperham/inspeqtor#82]
I found this a bit strange and we have it happens not to often but it still the boy how cried wolf so I figured I would bring it up.

Durning the deploy process we do inspeqtorctl start deploy which does what we expect. After which we tell sidekiq to shutdown using the sidekiqctl stop command that is within upstart tool. The problem comes in when we try to start sidekiq backup and tell inspeqtor that we are done with the deploy. 

We keep getting these emails based on however long it takes sidekiq to turn on.

    The sidekiq service is now running with PID 29487 

    Your Pal, 
    Inspeqtor 

What I was wondering is if there is a way to place a delay on inspeqtor to ask it for a grace period that makes it not notify us if the process come online within 15 or 10 seconds after telling inspeqtor are deploy is finished. 

Seams small but it makes it much easier to know which services are running incorrectly and which ones are having problems turning on.

**Comment by sorentwo** [comment]
@newdark: We had the exact same problem before upgrading to [v0.8.1-1](https://github.com/mperham/inspeqtor/blob/master/Changes.md#081-1). That does exactly what you're suggesting, adds a grace period to prevent the "cry wolf" scenario. Have you tried upgrading?

I can sympathize as I used to get dozens of notices a day before that fix.

**Comment by newdark** [comment]
No we have not did not know that it was in the newer versions thanks for the info.

**Comment by newdark** [comment]
Thanks for info it worked

**Comment by sorentwo** [comment]
@newdark: Great! Glad to help.
