### ISSUE TITLE
Command timeout in #7 causing false alarms

### ISSUE THREAD

**Issue by Zeelot** [mperham/inspeqtor#86]
Using `Inspeqtor 0.8.1` on Ubuntu 12.04.
#7 introduced a timeout to commands which causes issues for me when trying to restart services. My services actually take ~30 seconds to shut down and come back. It would be great to either look at the kill timeout value of Upstart init scripts or let me configure the timeout on a per-service basis. Thoughts? Currently, I am being stuck with false alarms where `inspeqtor` tries to restart a service, the command times out, `inspeqtor` alarms about not finding the process in the next cycle, `upstart` completes the restart, `inspeqtor` detects the new process and goes back to normal.

**Comment by mperham** [comment]
We could bump up the RestartTimeout from 10 to 30 but I get the feeling that would just push back the problem.  I don't like the idea of a configurable option either but I don't see any obvious way around it.  I'll think about it.

**Comment by Zeelot** [comment]
Yeah I'm pretty upset about these services taking 30 seconds to come down (they are `sidekiq` instances, by the way :P) but I'm just the DevOps guy and simply need to make sure things run smoothly.   The kill timeout in my init scripts is set to 60 for these particular services and although bumping the timeout from 10 to 30 might work for me right now, I agree that it would mostly just push back the problem.

**Comment by mperham** [comment]
:sunglasses: That's hilarious.  For the record, I do advise people to write idempotent jobs that can be terminated mid-point and restarted for exactly this reason.  You can't easily restart with an init system if the process takes minutes to "quiet" down.

**Comment by Zeelot** [comment]
Any other thoughts on this? We've made some adjustments that improved the shutdown speed quite a bit, but it's still not fast enough to avoid these false alarms :(

**Comment by mperham** [comment]
In this case, I'm silent because I don't know the right thing to do.

**Comment by sorentwo** [comment]
@Zeelot: Has anything changed here since May?

**Comment by Zeelot** [comment]
Not from what I can tell. Not a giant issue since most of our scripts do terminate quickly enough. Right now I am simply ignoring the errors and using Inspeqtor to restart services when they leak too much memory (most of our ruby applications). It doesn't seem like I can use this tool for alerting until this is solved but am not in a huge rush to do so anyway.
