### ISSUE TITLE
Illumos/Solaris support

### ISSUE THREAD

**Issue by bbhoss** [mperham/inspeqtor#87]
As a user of SmartOS, I would like to be able to use Inspeqtor to monitor my services, but it doesn't currently support SMF. We talked about Travis-CI not supporting Illumos being a potential issue. I don't think that a build service's limitations should be a product's limitations, but I understand time is not unlimited. I also see FreeBSD mentioned as untested (almost certainly due to the same Travis-CI limitations).

Can we discuss this, or possible other ways to use Inspeqtor on other OSes? I am willing to work on submitting a patch to support SMF and Illumos in general.

Would it be possible to make an abstract init system adapter where you could pass in custom options for doing the various things, such as getting the PID, reloading/restarting?

**Comment by mperham** [comment]
I'm happy to see this support if you're willing to author it and provide support when occasional SmartOS questions pop up.  I run CentOS 7 and Ubuntu 14.04 in production so those are the two systems I can support.

There's no abstract init adapter but there is an InitSystem interface which all adapters need to implement.  SMF support should be as simple as writing an implementation of that interface.

https://github.com/mperham/inspeqtor/blob/master/services/types.go#L54
