### ISSUE TITLE
Add support for Elasticsearch daemon specific metrics

### ISSUE THREAD

**Issue by sorentwo** [mperham/inspeqtor#88]
Having added this to our stack recently we of course want to get detailed metrics. There is a `/health` endpoint provided by the REST client.

[Documentation](http://www.elastic.co/guide/en/elasticsearch/guide/current/_cluster_health.html)

`curl -XGET localhost:9200/_cluster/health`:

```json
{
   "cluster_name": "elasticsearch",
   "status": "green",
   "timed_out": false,
   "number_of_nodes": 1,
   "number_of_data_nodes": 1,
   "active_primary_shards": 10,
   "active_shards": 10,
   "relocating_shards": 0,
   "initializing_shards": 0,
   "unassigned_shards": 0
}
```

Everything other than `cluster_name`, `status`, and `timed_out` seem like viable gauges.

**Comment by mperham** [comment]
No DSM requests, PRs only.

**Comment by sorentwo** [comment]
Sorry, this wasn't meant as a request. I started on implementing it around the same time. Afterwards I backed away from elasticsearch and returned to the beautiful comfort of Postgres.

**Comment by mperham** [comment]
Ha, yeah I've heard ES can be an beast to run/admin.

**Comment by sorentwo** [comment]
300mb of RAM per server for a single index is baffling to me. Maybe somebody else will feel drawn to the cause =)
