### ISSUE TITLE
Does inspeqtor support Upstart Instances?

### ISSUE THREAD

**Issue by newdark** [mperham/inspeqtor#89]
So in Upstart the tool has the abilty to create multiple instances using things like `start service_name INSTANCE=1`. However I can't find a way for inspeqtor to check that service. 

```go
check service service_name INSTANCE=1
  if memory:rss > 2g then alert
  if cpu:user > 90% for 2 cycles then alert
```

I can't find anything in the documentation and it looks like based on [the code](https://github.com/mperham/inspeqtor/blob/ecb024cbf5bd05617614d06b4ba636630199a4fb/services/upstart.go#L56) it does not support environment variables. That or I just can't figure out how to get the inspeqtor to use environment.

**Comment by mperham** [comment]
It doesn't support instances.  You'd need to create `service-0.conf`, `service-1.conf`, etc in `/etc/init` and have a separate inq for each.

**Comment by newdark** [comment]
ok I figured thought I would ask.
