### ISSUE TITLE
Configure Email Alert Port

### ISSUE THREAD

**Issue by bytenel** [mperham/inspeqtor#91]
Hey there! Is there a way to configure the port for emailing alerts via inspeqtor? I wanna setup the alerts but my email service uses port 465 to authenticate.

**Comment by mperham** [comment]
Indeed you can, the wiki was out-of-date and has been updated, you need to set the `tls_port` variable:

```
send alerts via email with 
  username bubba, password "correct horse battery staple", smtp_server smtp.example.com, 
  to_email accounting@example.com, tls_port 587
```

**Comment by bytenel** [comment]
Sick! Thanks for letting me know.
