### ISSUE TITLE
PagerDuty integration (channel)?

### ISSUE THREAD

**Issue by Zeelot** [mperham/inspeqtor#95]
PagerDuty is pretty good at figuring out who to contact and how. It would be great if inspeqtor alerts could be sent to PagerDuty to let it handle alerting and escalation there. Thoughts? Seems like inspeqtor could also resolve PD events if things get solved: https://developer.pagerduty.com/documentation/integration/events

**Comment by mperham** [comment]
Seems like a good idea.  Just to be transparent, support for non-email channels are considered a feature more relevant to teams and therefore a Pro feature.  https://github.com/mperham/inspeqtor/wiki/Development#pro-features

**Comment by Zeelot** [comment]
Thanks for the heads up
