### ISSUE TITLE
Slack Channel Instructions are confusing (or I'm an idiot)

### ISSUE THREAD

**Issue by zdavis** [mperham/inspeqtor#97]
On the Pro Channels page of your documentation, you say the following:

> Create a new Incoming Webhook integration on your Integrations page: https://$TEAMNAME.slack.com/services/new. Note the token for the created integration.

As far as I know, Slack doesn't return a token for an incoming webhook. Instead, it returns the URL for the webhook. Is that what should be assigned to the token value for the channel configuration?

Apologies in advance if I'm missing something obvious here...

**Comment by mperham** [comment]
Looksl ike Slack redid their webhook integration since that documentation was written 6 months ago.  I suspect that the token is the last portion of the URL.  Can you try that token and see if it works with the existing docs?  I suspect they'll be backwards compatible.

In the meantime I'll redo the Slack integration to be up-to-date.

**Comment by zdavis** [comment]
Yep, your hunch is right. With the last segment of the URL path, it's successfully sending messages to our slack room. Thanks, Mike.

**Comment by mperham** [comment]
:metal: I've already fixed the code and will update the docs when I get a new release out.

**Comment by keithpitt** [comment]
I actually just tried to setup Slack, but no dice. In the logs I see:

`Sending slack alert to https://buildkite.slack.com/services/hooks/incoming-webhook?token=xxx/xxx/xxx`

But nothing comes through. 

```
send alerts
  via slack with team buildkite, token xxx/xxx/xxx, icon_emoji ghost
```

I note that my token has `/` in it, could that be a problem?

**Comment by mperham** [comment]
I believe the token is the last element of that?

**Comment by zdavis** [comment]
Mike is correct—just the last segment worked for me.

**Comment by keithpitt** [comment]
![image](https://cloud.githubusercontent.com/assets/25882/7738435/7f58c064-ff54-11e4-9ce0-942ae552876d.png)

Oh wow! Yup, that was it!
