### ISSUE TITLE
Sidekiq monitoring

### ISSUE THREAD

**Issue by mkarklins** [mperham/inspeqtor#98]
Hi,

Right now I'm researching monitoring solutions, and I was wondering if Sidekiq integration is plausible. I've looked into [Sidekiq monitoring](https://github.com/mperham/sidekiq/wiki/Monitoring) and it seems that queue latency and backlog metrics, would be enough.

One other thing, we depend on a lot of external web services, and we'd like to keep an eye on them (if they are reachable). Based on wiki, seems that this kind of requirement would be out of Inspeqtor's scope.

**Comment by mperham** [comment]
You're right, Inspeqtor has a well-defined scope: it's designed to monitor processes and resources on localhost, not arbitrary application metrics.  I would consider Sidekiq metrics part of application metrics.

I would use something like Pingdom or UptimeRobot to monitor external services and track app metrics in something like Librato or Datadog.

**Comment by sorentwo** [comment]
This seems like a good time to mention that I'm working on adding Librato integration to Inspeqtor Pro. If you want to go that route in the meantime you can use the Librato backend for statsd.
