### ISSUE TITLE
Other ACTION for phased restart on puma

### ISSUE THREAD

**Issue by allaire** [mperham/inspeqtor#99]
Hi,

Due to some memory leaks in our Rails app, we often need to restart puma when the memory % is getting too high.

As you may know, puma has the concept of phased restart, where it kills each worker one by one. This restart mode is ideal to have zero impact on our users, since there is no hanging requests / downtime.

We currently have puma and sidekiq setup with foreman, which is responsible to export upstart on each deploy (using Capistrano). Here's my Capistrano task for puma: https://gist.github.com/allaire/97221660f058551c0c5f (take a look at `smart_restart` task).

Currently, puma is restarted with inspeqtor using the `restart` ACTION (which itself triggers a stop/start using our upstart script). I would love to have a mechanic similar to my capistrano tasks, where I can send a special signal to Puma if the pid is present (which would start a phased restart), or otherwise send a hard upstart restart.

Here's my current upstart script:

```
env PORT=5000
env PATH='/opt/rbenv/shims:/opt/rbenv/bin:/opt/rbenv/plugins/ruby_build/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games'
env RAILS_ENV='staging'
env RACK_ENV='staging'
...

setuid myapp

chdir /home/myapp/apps/web/current

exec bundle exec puma -p 5060
```

I don't see how I could put this smart restart mechanic in my upstart script, but this might be an option as well.

**Comment by sorentwo** [comment]
@allaire: A while back we implemented `reload` within Inspeqtor for this exact situation. I have a blog post that summarizes using Puma/Upstart/Inspeqtor all together, which may be of help: http://sorentwo.com/2014/12/08/self-healing-deployment.html

Let me know if you need any additional help. This is a use case for Inspeqtor that I'm particularly interested in.

**Comment by allaire** [comment]
@sorentwo thanks for that blog post! Are you still using that solution? Also, is the `reload` command working out of the box with inspeqtor? If so, it might be a good idea to write this down in the doc (that inspeqtor can forward any commands to upstart, if this is the case of course).

Thanks!

**Comment by sorentwo** [comment]
@allaire: Yes, I'm still using that exact solution in production and staging environments. The only time a hard restart is required is for a substantial update, like Puma. In that case the assets get out of sync, but the system still stays up.

The `reload` command has custom support in Inspeqtor. It isn't possible to forward any arbitrary command that upstart or an init script supports, the commands all need specific implementation within Inspeqtor. That is partially because of the syntax parsing, but also because some actions have different timing and other constraints.

**Comment by allaire** [comment]
@sorentwo Right, just peeked at the code, thanks.

When a hard restart is required, do you simply do a `sudo service puma-app restart`? I know that Puma has the concept of hot restart where no requests is lost (but hanging). I think upstart sends a SIGTERM when it hard restarts, does hot restart works with this?

**Comment by sorentwo** [comment]
@allaire: Yes, that's exactly what is used. Here is a gist of the [exact Capistrano tasks](https://gist.github.com/sorentwo/25a5d579ba84e4af8838) that are used. Instead of "hot " restarts we use "phased" restarts, which are similar to how Unicorn does restarts but only works with clustered mode. Triggering a phased restart is what the `reload signal USR1` portion of the upstart script is doing.

**Comment by allaire** [comment]
@sorentwo Much thanks for all your help, I think everything is pretty much figured out.

Just to clarify, when you do your `hard_restart` (`sudo restart puma`), no requests are lost, correct? I know they will hang (since this is not a phased restart), but I just want them to go through eventually :)

Finally, have you experienced with the preload!

**Comment by mperham** [comment]
Totally forgot about reload.  Thanks for reminding me, great use case.

**Comment by sorentwo** [comment]
Using `hard_restart` it is possible to lose some requests, just like if you were upgrading Unicorn. Unfortunately I don't know of a Ruby tool that allows for full binary swapping like Nginx does, or hot module replacement like Erlang.

That said, we do mitigate nearly all lost requests through multiple servers, load balancing, and doing rolling restarts. The load balancer will take any server with a `502` response out of the rotation for 15 seconds, which is more than adequate for Puma to pick back up the socket and start queueing requests. We only do a hard restart every couple of months and lose about requests in the process. If you have a flexible platform (or want to put in the engineering time) you could have Capistrano take each node out of the balancer before doing the restart. We haven't needed that level of absolute consistency though.

Regarding `preload!` it is very important that you *don't* use `preload!`, as it conflicts with `prune_bundler`, which you'll need to use in order for gem updates to work across phased restarts.

**Comment by allaire** [comment]
@sorentwo Great, I knew `preload!` was conflicting with phased restarts.

As for the `sudo restart puma`, isn't puma just queuing all the requests? (https://github.com/puma/puma/blob/75fa5fd2fd868c2a68dc1707d3cf7428a299dba6/README.md#restart) (hot restart).

**Comment by sorentwo** [comment]
Ha, I almost linked to that exact part of the Puma README before. You're absolutely right. Glad I could help otherwise!

**Comment by mperham** [comment]
You can get no downtime restarts if you use something like Stripe's [einhorn](https://github.com/stripe/einhorn) IIRC

**Comment by allaire** [comment]
@mperham Didn't know about this project, looks nice. I think you also use Puma, do you use einhorn with it or hot restarts (for hard restarts) and phased restarts are suffisant?

**Comment by mperham** [comment]
I don't use puma (currently) and have never used einhorn before.

**Comment by allaire** [comment]
@sorentwo Just implemented your solution and everything seems to work well! I'm wondering if `normal exit 0 TERM` is really required though? It seems to work without it, but I might be missing something :)

Thanks!

**Comment by sorentwo** [comment]
No, I don't think you need to set `TERM` explicitly for puma. I'd need to consult the upstart docs to be sure, but I think it defaults to `QUIT`, which also works.

I believe there is a difference for Sidekiq though. TERM will timeout after 8 seconds but QUIT will force immediate shutdown.

**Comment by allaire** [comment]
@sorentwo from what I see: http://serverfault.com/questions/189780/what-signal-does-upstart-initctl-use-to-restart-a-job — I'll leave the `normal exit` instruction, since I suppose if something stops abruptly, it will not send a SIGTERM :)

**Comment by allaire** [comment]
@sorentwo See for sidekiq: https://github.com/mperham/sidekiq/blob/master/examples/upstart/manage-many/sidekiq.conf#L33

**Comment by allaire** [comment]
@sorentwo So I suppose if I don't have the `normal exit` instruction for puma, upstart might try to restart puma at the same time that puma restart the worker process. I don't think this can lead to dangerous race condition, but I think it's safer to let puma restart what he wants during a phased-restart.

**Comment by evanphx** [comment]
@allaire There is so much going on in this issue. What is your question?

**Comment by allaire** [comment]
@evanphx I think everything's fine finally :)
